version: '3.7'
services:
  server:
    build: ./dtm_i4/Dockerfile
    restart: always
    ports:
      - target: 4001
        published: 4001
        protocol: tcp
        mode: host
      - target: 3001
        published: 3001
        protocol: tcp
        mode: host
    network_mode: host
  display:
    build: ./app-display/Dockerfile
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    network_mode: host
    environment:
      - SOCKET_PORT=4001
      - SOCKET_IP=server
